"""Add end_page column to document_chunks

Revision ID: e8f7c1f752f4
Revises: 439da9f4d286
Create Date: 2026-09-27 21:29:54.515838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f7c1f752f4'
down_revision: Union[str, Sequence[str], None] = '439da9f4d286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('end_page', sa.Integer(), nullable=True, comment='End page number of chunk'))
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               comment='Start page number of chunk',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'page_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Start page number of chunk',
               existing_nullable=True)
    op.drop_column('document_chunks', 'end_page')
    # ### end Alembic commands ###
