from abc import ABC, abstractmethod
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class LLMGenerationRequest(BaseModel):
    """Internal normalized payload sent to an LLM provider."""
    system_prompt: str = Field(..., description="System instructions and operational invariants")
    user_prompt: str = Field(..., description="Encapsulated evidence context and user query")
    temperature: float = Field(0.0, description="Sampling temperature (0.0 for deterministic factual output)")
    max_output_tokens: int = Field(1024, description="Maximum token limit for model response")
    stop_sequences: Optional[List[str]] = Field(None, description="Optional stop sequences")

    model_config = ConfigDict(from_attributes=True)


class LLMGenerationResponse(BaseModel):
    """Internal normalized completion returned by an LLM provider."""
    content: str = Field(..., description="Raw text generated by the language model")
    prompt_tokens: int = Field(..., description="Estimated or reported input prompt token count")
    completion_tokens: int = Field(..., description="Estimated or reported output completion token count")
    total_tokens: int = Field(..., description="Total token consumption")
    model_name: str = Field(..., description="Model identifier used for generation")
    finish_reason: str = Field("stop", description="Reason model stopped generating ('stop', 'length')")
    latency_ms: float = Field(..., description="Provider generation latency in milliseconds")

    model_config = ConfigDict(from_attributes=True)


class BaseLLMProvider(ABC):
    """Abstract base protocol for LLM completions."""

    @abstractmethod
    def generate(self, request: LLMGenerationRequest) -> LLMGenerationResponse:
        """Execute synchronous LLM text generation."""
        pass

    @abstractmethod
    async def agenerate(self, request: LLMGenerationRequest) -> LLMGenerationResponse:
        """Execute asynchronous LLM text generation."""
        pass
